### PR TITLE
Support for Rails 5.2, 6.0, 6.1, drop support for older Rails

### PR DESCRIPTION
**Pull request by puyo**
- [x] replaced .haml files with .erb files
- [x] replaced various .coffee files with one rewritten and simpler .js file
- [x] testing it out on jupiter / staging

### CODE REVIEW

**Comment by puyo** [comment]
```
$ be rake test
Started with run options --seed 2692

when replying
  test_0003_has the reply in the @recipient's outbox              PASS (0.08s)
  test_0004_has ancestry tree                                     PASS (0.04s)
  test_0001_reply to sender                                       PASS (0.05s)
  test_0002_is delivered to @sender                               PASS (0.05s)

with messages
  test_0011_sends a draft                                         PASS (0.15s)
  test_0012_edits a draft                                         PASS (0.05s)
  test_0009_redirects to show view if uneditable?                 PASS (0.04s)
  test_0002_sees an outbox                                        PASS (0.04s)
  test_0014_replies                                               PASS (0.08s)
  test_0007_views a sent message                                  PASS (0.04s)
  test_0010_redirects to edit view if unsent?                     PASS (0.04s)
  test_0004_sees trash                                            PASS (0.06s)
  test_0001_redirects to inbox if message is not mine             PASS (0.04s)
  test_0005_moves a message to trash                              PASS (0.05s)
  test_0008_views a recieved message                              PASS (0.05s)
  test_0003_sees drafts                                           PASS (0.04s)
  test_0006_empties trash                                         PASS (0.06s)
  test_0013_does not see reply form if I sent the message         PASS (0.04s)

sender::when draft::without recipients
  test_0001_saved message as draft when no recipients             PASS (0.02s)
  test_0002_does not deliver                                      PASS (0.02s)

sender?
  test_0001_inbox                                                 PASS (0.03s)
  test_0004_trash                                                 PASS (0.03s)
  test_0002_outbox                                                PASS (0.03s)
  test_0005_can empty_trash!                                      PASS (0.04s)
  test_0003_drafts                                                PASS (0.03s)

with users::when sent
  test_0002_cannot go back to being a draft once sent             PASS (0.02s)
  test_0001_cannot be edited once sent                            PASS (0.02s)

WorkFlowTest
  test_0001_seeing an empty inbox                                 PASS (0.02s)

sender::when deleted
  test_0003_still appears in the recipient inbox                  PASS (0.04s)
  test_0002_is not included in the #trash scope                   PASS (0.03s)
  test_0001_can be deleted                                        PASS (0.03s)

sender::when trashed
  test_0001_still appears in the recipient inbox                  PASS (0.03s)

sender?
  test_0001_has a root                                            PASS (0.04s)
  test_0002_can find all conversation-related messages            PASS (0.04s)
  test_0003_find messages the user owns                           PASS (0.04s)
  test_0004_places messages in the correct mailbox                PASS (0.04s)

new message
  test_0001_composes a draft                                      PASS (0.05s)
  test_0002_sends a message                                       PASS (0.05s)

with users::when sent::when received
  test_0001_cannot be edited                                      PASS (0.03s)

Discuss::MessageTest
  test_0001_must be valid                                         PASS (0.01s)
  test_0002_is read! once                                         PASS (0.03s)

recipient?
  test_0001_has a root                                            PASS (0.04s)
  test_0003_find messages the user owns                           PASS (0.04s)
  test_0002_can find all conversation-related messages            PASS (0.04s)
  test_0004_places messages in the correct mailbox                PASS (0.04s)

Discuss::RecipientTest
  test_0002_does not deliver if no :body                          PASS (0.03s)
  test_0001_cannot reply if no parent                             PASS (0.03s)
  test_0003_has a parent message                                  PASS (0.03s)

DiscussTest
  test_truth                                                      PASS (0.00s)

sender?::when not message owner
  test_0001_still find the correct messages                       PASS (0.04s)
  test_0002_trashes the conversation                              PASS (0.05s)

draft
  test_0001_returns proper user depending if there are recipients PASS (0.02s)

sender::when draft::with recipients
  test_0003_when trashed, should not be included in the #drafts scope PASS (0.02s)
  test_0001_defaults to draft                                     PASS (0.02s)
  test_0002_should not deliver the message                        PASS (0.02s)

with users
  test_0001_should have a user                                    PASS (0.01s)

sender::when sending
  test_0003_sets sent_at but not received_at                      PASS (0.03s)
  test_0002_can have multiple recipients                          PASS (0.03s)
  test_0004_is included in the #sent scope                        PASS (0.03s)
  test_0001_sends a message by calling #send!                     PASS (0.03s)
  test_0005_when trashed, should not be included in the #outbox scope PASS (0.03s)

with users::when sent::when received::conversation
  test_0001_has correct recipients size                           PASS (0.05s)

recipient?
  test_0001_inbox                                                 PASS (0.03s)
  test_0002_outbox                                                PASS (0.03s)
  test_0005_can empty_trash                                       PASS (0.04s)
  test_0003_drafts                                                PASS (0.03s)
  test_0004_trash                                                 PASS (0.03s)

message held by multiple threads
  test_0001_can only be sent once                                 PASS (0.02s)

Discuss::ConversationTest
  test_0001_has total of 4 messages                               PASS (0.04s)

Finished in 2.59323s
69 tests, 138 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/greg/Blake/discuss/coverage. 258 / 287 LOC (89.9%) covered.
```

**Comment by puyo** [comment]
Kinda want to merge this into `wf-models` or `wf-student` but oh well.

**Comment by jestingrabbit** [comment]
incredible diff.

**Comment by puyo** [comment]
I'll try it out hopefully this week and see if it actually works. :P :)

**Comment by puyo** [comment]
Seems to work fine.

**Pull request merged**
